sync

diff --git a/bin/edit-script b/bin/edit-script
--- a/bin/edit-script
+++ b/bin/edit-script
@@ -5,7 +5,7 @@ set -e
 [[ -z ${TRACE:-} ]] || set -x
 
 usage() {
-	cat >&2 - <<EOF
+  cat >&2 - <<EOF
 USAGE:
     $(basename "$0") [FLAGS] FILE...
 
@@ -15,57 +15,55 @@ EOF
 }
 
 error() {
-	printf >&2 '%s: %b\n' "$(basename "$0")" "$1"
-	printf >&2 "Try '%s --help' for more information\\n" "$(basename "$0")"
-	exit 1
+  printf >&2 '%s: %b\n' "$(basename "$0")" "$1"
+  printf >&2 "Try '%s --help' for more information\\n" "$(basename "$0")"
+  exit 1
 }
 
 main() {
-	local scripts=()
+  local scripts=()
 
-	[[ $# -gt 0 ]] || error "missing file operand"
+  [[ $# -gt 0 ]] || error "missing file operand"
 
-	for arg; do
-		case "$arg" in
-		-h | --help)
-			usage
-			exit 0
-			;;
-		-*)
-			error "invalid option -- '$arg'"
-			exit 1
-			;;
-		*)
-			scripts+=("$arg")
-			;;
-		esac
-	done
+  for arg; do
+    case "$arg" in
+    -h | --help)
+      usage
+      exit 0
+      ;;
+    -*)
+      error "invalid option -- '$arg'"
+      exit 1
+      ;;
+    *)
+      scripts+=("$arg")
+      ;;
+    esac
+  done
 
-	local script
-	for script in "${scripts[@]}"; do
-		mkdir -p "$(dirname -- "$script")"
+  local script
+  for script in "${scripts[@]}"; do
 
-		if ! [[ -f $script ]]; then
-			case "$(basename "$1")" in
-
-			*.*)
-				echo '#!/usr/bin/env '"${1##*.}"
-				echo
-				;;
-			*)
-				echo '#!/usr/bin/env bash'
-				echo
-				echo 'set -e'
-				echo
-				;;
-
-			esac >>"$script"
-		fi
-
-    if "${EDITOR?}" -- "$script"; then
+    if ! [[ -f $script ]]; then
+      mkdir -p "$(dirname -- "$script")"
+      touch "$script"
       chmod +x "$script"
+      case "$(basename "$1")" in
+      *.*)
+        echo '#!/usr/bin/env '"${1##*.}"
+        echo
+        ;;
+      *)
+        echo '#!/usr/bin/env bash'
+        echo
+        echo 'set -e'
+        echo
+        ;;
+      esac >>"$script"
     fi
-	done
+
+    "${EDITOR?}" -- "$script"
+  done
 }
 
 main "$@"
