pbcopy shim

diff --git a/tag-debian/bin/pbcopy b/tag-debian/bin/pbcopy
--- a/tag-debian/bin/pbcopy
+++ b/tag-debian/bin/pbcopy
@@ -1,3 +1,13 @@
 #!/bin/sh
 
-exec xclip -selection clipboard
+# stub for muscle memory 
+has() { hash "$1" >/dev/null 2>&1; }
+
+if has xclip; then
+  exec xclip -in -selection clipboard
+elif has xsel; then
+  exec xsel --clipboard --input
+else
+  echo "$0: error: unable to find 'xclip' or 'xsel' on path"
+  exit 1
+fi
