fix script/bootstrap for linux platform

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -117,8 +117,8 @@ install_dotfiles () {
   done
   
   # prevent compaudit warnings
-  chmod g-w "$DOTFILES/functions/*"
-  chown "$(whoami)" "$DOTFILES/functions/*"
+  chmod -R g-w "$DOTFILES/functions"
+  chown -R "$(whoami)" "$DOTFILES/functions"
 }
 
 ################################################################################
@@ -127,7 +127,11 @@ echo ''
 chsh -s /usr/bin/zsh
 setup_gitconfig
 install_dotfiles
-$DOTFILES/script/install
+sh -c "$DOTFILES/script/install"
 
-success "done!"
-echo ''
+platform_script="$DOTFILES/script/bootstrap.$PLATFORM.sh"
+if [[ -x "$platform_script" ]]; then
+  info "running $platform_script"
+  "$platform_script" || fail "errored $platform_script"
+  success "ran $platform_script"
+fi
diff --git a/script/install b/script/install
--- a/script/install
+++ b/script/install
@@ -7,11 +7,12 @@ set -eu
 source "$(dirname "$0")/common.sh"
 cd "$DOTFILES"
 
-for installer in $(find . -name install.sh); do
-    if [[ -x "$installer" ]]; then
-        info "running $installer"        
-        sh -c "${installer}"
-    else
-        warning "$installer is not executable"
-    fi
+for installer in */install.sh; do
+  if [[ -x "$installer" ]]; then
+    info "installing $(basename "$(dirname "$installer")")"
+    sh -c "$installer" || fail "errored $(realpath "$installer")"
+    success "ran $(realpath "$installer")"
+  else
+    warning "skipped $installer (reason: not executable)"
+  fi
 done
